name: Vite issues
on:
  issues:
    types: [opened, edited, milestoned,closed]
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: git Hub details
        run: echo ${{ toJson(github)}}
