name: Vite practice
on: push
  jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: gitbub/checkout@v3
      - name: setup node Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: intall dependencies
        run: npm install
      - name: lint
        run: npm run lint
      